### ISSUE TITLE
Adding extra tests in test_types.c to confirm the functionality of Lua in our final demo

### ISSUE THREAD

**Issue by tatmaca** [uchicago-cs/chiventure#1707] opened 2022-05-28 20:39 UTC
Due to the new changes in the demo (integrating dark_room.c and gold.c with demonstration.c) and earlier difficulties implementing Lua functionality with WDL, these additional tests confirms the working status of the demo, particularly after further added functionality and final edits.

**Comment by jackjackkimkim** [comment] 2022-05-30 05:24
this issue was a duplicate of issue #1702

**Closed as completed** 2022-05-30 05:52 UTC
Labels: duplicate, x/custom-scripts

**Comment by ecoble** [comment] 2022-06-07 01:47
Removing the milestone of this duplicate issue, it will be ungraded.
