### ISSUE TITLE
develop action_effects

### ISSUE THREAD

**Issue by a-matai** [uchicago-cs/chiventure#316] opened 2019-06-08 20:16 UTC
The goal of this issue is to take over the effects code from #215 to break it into a smaller issue.

These are the necessary changes that need to be made to the effects:

effect_t {
item_t *item (for debugging purposes more than anything)
attr_t *attr_to_modify (pointer to the actual attribute from the item)
attr_value new_value (self explanatory)
}

the effect struct will be similar. The key difference is instead of holding a new attribute, we will point directly to the attribute in question. 

A few key things to work on here: 
- need to write all code for new effects list
- write code that takes in an effect and modifies an attribute
- same pointer issue as #315 (defer to @liuyifan-eric )

**Comment by Kate32815** [comment] 2019-06-08 20:49
WDL would like a function called *add_action_effect()* to facilitate the process of loading action effects into game state structs:

*add_action_effect()*

This function creates a new effect for an action (belonging to an item) and adds it to the list of effects for that action.

Parameters:
- g: pointer to a game state game struct
- item_id: the ID of the item we are performing the action on
- action_name: the name of the action for which we are adding effects
- eff_item_id: the ID of the item specified in the action effect
- eff_attribute: the attribute of the item specified in the action effect that needs to be modified
- eff_value: the value of the above attribute that needs to be modified

Output:
- 0 upon SUCCESS
- 1 if the first item ID (item_id) does not exist
- 2 if the specified action (action_name) does not exist in the first item
- 3 if the second item ID (eff_item_id) does not exist

Side Effects:
- Creates an action effect from input parameters (eff_item_id, eff_attribute, and eff_value) and adds it to the effect list for the specified action in the specified item
`int add_action_effect(game_t* g, char* item_id, char* action_name, char* eff_item_id, char* eff_attribute, char* eff_value);`

**Comment by MTUC08** [comment] 2019-06-08 21:05
Since all of our functions depend on this struct, please keep us updated on what the structs are going to look like and the names of all the components as well as what branch the code is being created on

**Comment by SnowballAntrobus** [comment] 2019-06-08 21:36
For testing purposes, action management needs a function that adds to the effect list of a game_action.

**Comment by a-matai** [comment] 2019-06-09 01:06
updates:

wrote helper function create_effect that will be used in add_action_effect. This can also be used standalone.

wrote function affect_effect that takes in an effect and, well, affects the given item. 

**Notes on add_action_effect**
It is unresolved how to add it to the list. This is left to @patrickkoopmans !

**Comment by a-matai** [comment] 2019-06-09 02:11
@Kate32815 given your request, we had to move add_effect into game.h. This is as per your request.

We also have an add_action_effect that takes the pointers to items themselves that has stayed in game_action.h. 

Feel free to use either but we haven't finalized them yet!

**Comment by patrickkoopmans** [comment] 2019-06-09 05:01
**Done:** 

1. do_all_effects() written (formerly called set_all_effects)--> this function takes in an item and an action and carries out every single effect associated with the action. meant to be used after check_all_conditions
2. do_effects() edited (formerly called affect_effects) --> now do_effects() no longer uses the set_x_attr functions as this takes extra steps to search item hashtables for attributes that we already have access to 
3. add_action_effect() finished --> as @a-matai requested, I have finished this function so that it actually adds the new action to the list of actions
4. Prototypes refectored --> several functions such as game_action_new() belong in our internal header file, common_game_action, rather than the public interface. I have made this header file and added a few functions to it from game_action.h

**To-do:** 
1. (NEED RESPONSE FROM WDL AND AM) What should the parameters for do_all_effects() be? Currently it is: item_t* item, char* action_name
2. What should the parameters of add_action_effect be? Please see my comment in game-action.c about this located right above the beginning of the function implementation.

**Comment by a-matai** [comment] 2019-06-09 19:39
Updated add_effect in game.h to take in attribute_name instead of ptr to attribute.
@Kate32815 please take a look at add_effect in game.h!

@patrickkoopmans wrt 2: I think it's fine to keep both for debugging purposes. because if you look at add_effect in the abstracted version, add_action_effect just takes in all the found pointers.

**Comment by Kate32815** [comment] 2019-06-09 20:15
@a-matai 
I was okay with the version without the abstractions but this works too! One thing is that the effect item id or pointer currently will not work, as the item to be modified does not have to be in the current room. 
I'm communicating with Patrick on how to fix this right now, and i think a new item hash table will be created in the game struct

**Comment by a-matai** [comment] 2019-06-09 21:08
Okay! Easy fix then.

The version without abstractions is in game_action.c
________________________________

**Comment by MTUC08** [comment] 2019-06-09 21:29
AM here:
- the current implementation of do_all_effects(item, action_name) is great!
- to confirm do_effect handles a singular effect input and is otherwise identical to do_all_effects (in what it does) right?

**Comment by jessxia** [comment] 2019-06-10 00:22
@MTUC08 Yep -- do_effect causes one effect to be implemented and do_all_effects called do_effect on each effect in the action's linked list.

**Comment by jessxia** [comment] 2019-06-10 00:28
Edited add_effect function to no longer take in room_id. Function now calls get_item_from_game to access item pointers from the game struct's new item hash table.

**Comment by Kate32815** [comment] 2019-06-10 05:24
Looks good! one small thing that won't really affect how we use it-- can the return int values for add_effect be changed to be from 0-4? (unless there is something else that should be returning 1)

**Comment by jessxia** [comment] 2019-06-10 06:22
Closing statement:
We continued our work on the game-state/develop_actions branch and finalized the game_action_effect struct to be:

- a pointer to the item whose attribute we will be changing
- a pointer to the attribute of the item that we want to change
- the new value of the attribute
- a pointer to the next effect in the list (it was confirmed that we needed this in order to use utlist macros)

We added or edited the following functions, mostly in game_action.c, to support use of our effect struct:

- do_effect, which carries out an effect of an action
- do_all_effects, which calls do_effect on all effects in an action's effect linked list
- effect_new, which mallocs space for a new effect and initializes it with given inputs
- add_action_effect, which adds an effect to an action's effect linked list and calls effect_new
- add_effect, a more abstracted version of the above function that takes in a game struct as well (in game.c)

If any further functions become necessary, we will implement them in a new issue.

**Closed by jessxia** 2019-06-10 06:22 UTC
Labels: component/game-state

**Comment by jessxia** [comment] 2019-06-10 21:37
Add_effect once again returns error codes SUCCESS and 2-5 since add_condition_effect may return FAILURE (which is 1). (Latest code is now on game-state/dev branch)

**Comment by lydiafilipe** [comment] 2019-06-17 01:17
Issue Score: ✓+

Comments:
Nice work! Great discussions
