### ISSUE TITLE
print_to_cli in operation.c

### ISSUE THREAD

**Issue by Tianlel** [uchicago-cs/chiventure#356] opened 2019-06-11 17:11 UTC
print_to_cli does not print anything in operations.c

**Comment by ecoble** [comment] 2019-06-11 18:07
UPDATE: print_to_cli works when it is called in cmd.c, but does not work anywhere it is called in operations.c. I have been debugging and seems like the string is being passed to print_to_cli, I cannot tell why it is not printing to the window. Worst case if we can't get this solved we try to route all our print_to_cli functions in operations.c out to cmd.c

**Comment by ecoble** [comment] 2019-06-11 18:08
Also a change that needs to happen anyways is printing action management's success and error strings, so I am going to make that change now

**Comment by ecoble** [comment] 2019-06-11 18:56
UPDATE: So I've realized the issue is not that our strings aren't printing, but that if we have multiple print_to_cli calls without a prompt between them, they overwrite each other and it appears as though only the last call to print_to_cli works. This is a UI fix so I will need their help.

**Comment by ecoble** [comment] 2019-06-12 00:08
UPDATE: Fixed the issue, UI now moves the cursor down after each output, instead of at the beginning of each prompt

**Comment by ecoble** [comment] 2019-06-12 03:15
CLOSING STATEMENT: We are now able to have multiple calls to print_to_cli in a row, without each call overwriting the last one. This was fixed by moving the cursor down after each output, instead of at the beginning of each input.

Note: I think this introduced a bug with the help text, need more UI help on that

**Closed by ecoble** 2019-06-12 03:15 UTC
Labels: bug, component/cli, component/ui

**Comment by lydiafilipe** [comment] 2019-06-14 03:05
Issue Score: ✓+

Comments:
Great work!
