### ISSUE TITLE
GUI: Modular Design For GUI Part 2

### ISSUE THREAD

**Issue by dhirpalshah** [uchicago-cs/chiventure#1299] opened 2022-05-06 01:16 UTC
For Sprint 3, we want to begin implementing important graphic features with testing inputs. The six modules we want to implement are for the creation of an inventory, display of scenes, drawing of NPCs, display of maps, quest lines (which will be in tandem with quests team), and the player stats (which will be in tandem with the action management team). Attached below is our modular design.
![Image from iOS](https://user-images.githubusercontent.com/86183980/167051137-bcae8406-56d8-4bd9-a376-3ca0bb397dda.jpg)

**Comment by cyruszzhou** [comment] 2022-05-09 12:51
We have successfully communicated with our teammates, and are currently implementing this under the graphcis_sandbox folder in the graphics_sandbox branch. Different members are assigned to different modules.

**Comment by cyruszzhou** [comment] 2022-05-09 12:51
The issue is closed as this modular design is adopted to be what we will be working on.

**Closed as completed by cyruszzhou** 2022-05-09 12:51 UTC
Labels: x/graphics x/gui
