### ISSUE TITLE
cli: implement function to change game mode to battle on user input (battle team request)

### ISSUE THREAD

**Issue by katyashchukina** [uchicago-cs/chiventure#1298] opened 2022-05-06 01:10 UTC
Team members: Brianna, Kate, Faruk

Our goal is to meet with the RPG battle team to discuss their requests and implement them as we are able. They want to implement a run_battle function that will run a battle with an NPC from start to finish. Our side is to implement a function that will take the inputted "fight npc_name" command, parsed and put into an array of strings, and subsequently change the game state to BATTLE mode.

**Comment by katyashchukina** [comment] 2022-05-06 01:15
Brianna and I met with the battle team today to discuss their requests. They want a battle loop that allows the user to pick fighting methods from a list and then return a string. 

Their design doc for this lists this in more detail: https://github.com/uchicago-cs/chiventure/wiki/Battles-~-CLI-Integration-Design-Document

Additionally we talked about how this task mimics the npc dialogues implemented with cli in a previous term. TODO: research this to see what they did

**Comment by katyashchukina** [comment] 2022-05-06 01:27
Looking into how npc dialogues were implemented:

The npc and cli were linked in game state. Here is an example function that parses the user's input and run's the next step of a conversation.

int run_conversation_mode(char *input, cli_callback callback_func, 
                          void *callback_args, chiventure_ctx_t *ctx)
{
    char **parsed_input = parse(input);
    if (parsed_input == NULL)
    {
        return FAILURE;
    }
    
    int option, num_options, rc;
    option = atoi(parsed_input[0]);

    npc_t *npc = get_npc(ctx->game, ctx->game->mode->mode_ctx);
    num_options = npc->dialogue->cur_node->num_edges;

    if ((option <= 0) || (option > num_options) || 
        parsed_input[1] != NULL) 
    {
        return callback_func(ctx, "Enter a valid dialogue option.", callback_args);
    }

    int end_convo;
    char *outstring = run_conversation_step(npc->dialogue, option, &end_convo, ctx->game);

    assert(end_convo != -1); //checking for conversation error

    /* Print npc dialogue and dialogue options */
    rc = callback_func(ctx, outstring, callback_args);

    free(outstring);

    /* If conversation over, switches back to normal mode */
    if (end_convo)
    {
        rc = set_game_mode(ctx->game, NORMAL, NULL);
    }

    return SUCCESS;
}

Here we see the first line char **parsed_input = parse(input); parses the input and is pretty much all that is required from our team.

Because the commands and responses the battle team has asked for is pretty rigid (see design doc) this should be doable within the current cli framework

**Comment by bzeng6** [comment] 2022-05-13 03:53
I have created a cli/battle_integration branch. 

The plan is to create a function similar to the talk_operation function in operations.c. The function will take a list of tokenized commands and a chiventure context struct. It'll read an inputted NPC's name from the commands, make sure that the NPC is in the room and willing to fight (and if not, returning text that says so), and then change the game mode to BATTLE and call the run_battle function that the battle team is making. Currently the return type will be void, though that is TBA.

Edit: I think that the functions in the operations.c file all take in arrays of token strings, not a tokenized_cmd struct, so I'm just going to follow the existing structure with that.

**Comment by bzeng6** [comment] 2022-05-13 03:57
The existing talk_operation function relies on a function called get_npc_in_room, which presumably is supposed to return a pointer to an npc_t struct if an npc with a given name is found in the current room. If the npc name is not found in the room, it returns NULL, and the talk_operation function returns a string that says that it can’t find an npc to talk to with that name. But I can’t seem to find the function in any of the npc files. I'm not sure if it got backlogged and never implemented, or if it's a different file than I'm checking.

This means that we will either have to request npc team to create a function like this, or we make a work-around where we check ourselves whether the npc is in the room.

**Comment by bzeng6** [comment] 2022-05-13 05:40
I have created an initial implementation of a battle_operation function. It checks whether the user inputted the name of an opponent to battle, whether there is an NPC with the inputted name in the room, and whether the NPC is willing to fight (npc_t struct will_fight element). It then sets the game mode to BATTLE mode. 

Concerns:
- The npc_t struct isn't initialized with an npc_battle item in the struct. Will the battle team implement this on their side or should we add it?
- I'm not sure if the npc team has updated the set_game_mode function to include BATTLE mode yet, though BATTLE mode should already be a valid mode type.
- What function should be called to actually start the process of the battle? run_battle?
- What should the return value be? Currently set as void but I realize that it should be char * if it wants to output strings notifying if npc doesn't exist and stuff.

Github run link: https://github.com/uchicago-cs/chiventure/actions/runs/2317613757

**Comment by katyashchukina** [comment] 2022-05-13 20:14
We have responses from the battle team! 

- set_game_mode in mode.c doesn't accommodate battle mode (it is unclear if they want us to do something about this, Brianna and I think this is potentially a job for the NPC team but I have asked the battle team just to be clearer on boundaries)
- For the NPC, there is run_conversation_mode in mode.c as well TODO: check it out

**Comment by bzeng6** [comment] 2022-05-14 03:11
We checked out run_conversation_mode and it looks like this is the function that the Battle team will be basing their run_battle function off of, which is not so consequential to our implementation.

We changed the return type of our function battle_operation to char *, so that we can return strings to be printed to the command line. We also fixed a small typo in an npc name. This fixes the compilation errors. You can see the run here: https://github.com/uchicago-cs/chiventure/actions/runs/2322695157

Also, the battle team informed us that by us changing the game state to BATTLE mode, that should automatically call a function that will initialize and run a new battle, so there is no need for us to call a function to do so in our end of the implementation. 

Looks like the only thing stopping the function from working as intended is the set_game_mode function, which as mentioned does not support changing into BATTLE mode yet. But once game state team finishes that, it should work.

**Comment by majorsylvie** [comment] 2022-05-16 15:39
Created base pull request for just the framework. 
Link found here: https://github.com/uchicago-cs/chiventure/pull/1404

Still need to do work with the surrounding code to make sure that the `fight` operation is recognized by chiventure

**Comment by bzeng6** [comment] 2022-05-16 17:35
I think there is a function in cmd.c, lookup_t_init that links action verbs to certain functions.

I think if you add a verb and function pair to the lookup_t struct, you might be able to cmd_from_tokens to create a cmd struct for that given action command verb. Since cmd_from_tokens calls assign_action (operations.c) which calls find_operation (cmd.c) which returns a certain function in the lookup_t hashtable struct, and assigns the func_of_cmd item in the cmd struct to that function. assign_action also calls cmd_new, which creates the new cmd and also initializes the tokens item in the cmd struct to a given action command token.

**Comment by bzeng6** [comment] 2022-05-18 07:10
In the lookup_t_init function, I added a call to add_entry with arguments command text "FIGHT", associated operation battle_operation, action type NULL, and lookup_t struct parameter t. This should add the action command "FIGHT" and link it to the function battle_operation in the lookup_t hashtable of actions struct.

The lookup_t_init function directly adds operations to the lookup_t struct that are not of action type 1, 2, or 3. It then calls add_action_entries which adds all actions of type 1, 2, or 3 into the table. The command "TALK" is also initialized here—I did the same for "FIGHT" because they don't fit into action type 1, 2, or 3 (or 4, which is being developed alongside action management and the cli view stats team right now), since it its second token is an npc, not an item or direction. So, I'm not sure if a new action type should be created for ACTION <npc> type actions.

Now when you run chiventure using an example wdl, typing "fight" should call the function battle_operation:

<img width="857" alt="Screen Shot 2022-05-18 at 1 59 20 AM" src="https://user-images.githubusercontent.com/96360414/168978647-6b91a46d-2fc2-4b8a-81fe-6be69b3928c0.png">

**Comment by bzeng6** [comment] 2022-05-18 07:32
Current concerns: 

Should a new action type be created for ACTION <npc> type actions?

Find or create a wdl file that actually includes npc's so that other outputs of the battle_operation function can be tested, like if the npc is found but doesn't want to battle, or if they do want to battle and test if it prints that it started the battle, the final return value string (even though it physically won't change the game mode and start the battle since that function hasn't yet been implemented).
- Currently I've only tried typing "fight" on classes.wdl and connected-rooms.wdl, and it registers as a command, but I'm not sure if it will work for other wdl files.

**Comment by bzeng6** [comment] 2022-05-22 05:00
I fixed the code based on PR comments:

I made the fight_operation function assert that the npc_battle struct in the npc is not NULL before the function returns.

I fixed a typo in the header file.

**Comment by bzeng6** [comment] 2022-05-24 06:32
Recently there was a [change](https://github.com/uchicago-cs/chiventure/issues/1397) to the npc struct that changed the will_fight bool to a hostility_level bool. I adjusted the reference to this struct item accordingly, to make sure that the npc hostility_level is on HOSTILE mode before changing the game mode to BATTLE.

**Comment by bzeng6** [comment] 2022-05-24 07:07
Closing statement:

We think this issue is ready to close because now that the build issues are fixed and the operation is added to the lookup_t hash table, the function is fully implemented. It properly checks whether a given npc is in the current room and whether they are hostile (willing to fight) before changing the game mode to BATTLE.

Brianna and Kate primarily dealt with meeting with the Battle team and documenting their requests, as well as implementing the new operation function. Faruk did research and implementation work on how to get chiventure to actually recognize the "fight" action and adding the function to the lookup_t hash table. Brianna responded to PR comments.

**Closed as completed** 2022-05-24 14:05 UTC
Labels: x/cli, x/cli++

**Comment by jacknugent1529** [comment] 2022-06-06 15:41
Issue Score: Excellent

Comments: Fantastic work on this issue! The updates are very well written and explain your progress very well. You also did a great job of linking relevant documents and resources.
