### ISSUE TITLE
Design the WDL interface for quests

### ISSUE THREAD

**Issue by JSerf02** [uchicago-cs/chiventure#1265] opened 2022-05-02 22:50 UTC
We need to figure out how to represent quests in a JSON file. In particular, we need to find a clean way of representing the complex quest multitrees, prerequisites, and rewards.

**Comment by Castel-Jaloux** [comment] 2022-05-13 21:04
We have created an outline for the design document detailing the basic aspects necessary for the WDL representation. The next step is to create the document itself and upload it to the wiki for broader visibility.

**Comment by Castel-Jaloux** [comment] 2022-05-13 22:08
The design document has been completed and uploaded to the wiki.

**Comment by JSerf02** [comment] 2022-05-15 07:22
We just updated the [Wiki](https://github.com/uchicago-cs/chiventure/wiki/Quests-~-WDL-Representation-Design) with better formatting and more specific examples

**Comment by charlieweiler** [comment] 2022-05-15 22:09
We have reviewed the Wiki and have a good general outline of the JSON-compatible format needed to specify quests in the WDL. The task tree, as well as the tree, mission, and rewards structs have been designed, along with a way to store prerequisite tasks in a hashtable. The functions at the bottom of the Wiki will be instrumental in implementing this design in a future issue. As such, the issue is closed.

**Closed as completed by charlieweiler** 2022-05-15 22:09 UTC
Labels: x/quests

**Comment by philipchenaux** [comment] 2022-05-24 20:39
Issue Score: Excellent

Comments:
Great job, and a very thorough wiki! I would advise next time just including a brief summary of what you added to the wiki instead of just saying that the wiki was updated, but this is a very minor detail!
