### ISSUE TITLE
Implement a new action "view skills" along with the skilltrees team

### ISSUE THREAD

**Issue by HarrisonD123** [uchicago-cs/chiventure#1625] opened 2022-05-25 21:32 UTC
Our goal here is to allow the user to view the names of the skills in their skilltree.

In order to implement this, the skilltrees team would have to create a display skilltree function in the game-state/player module that we can call from the action_management/actionmanagement module. We would have to modify the logic within the if-statement of our do_self_action function to accommodate this and to call this display function.

Because we won't be able to display all skills and their descriptions in one print to the terminal, we also want to implement a `"view skills "description""` command, which will call the skilltree team's `display_skill_description` function and print the description of a specific skill.

**Comment by HarrisonD123** [comment] 2022-05-25 22:22
After talking with the skilltrees team, we decided to have them make 2 functions, one to display a list of all skills and one to display the description of a specific skill. We will call the correct function based on the number of inputs our `do_self_action` function is given.

**Comment by jbrouwer5** [comment] 2022-05-25 22:31
We implemented two new functionalities within our do_self_action function in order to view skill trees and a description of a specific skill. The code is not currently building because the new display functions in the skill trees module have not been merged to dev yet. Once CLI and Skilltrees merge their respective work our code should work as intended.

**Comment by HarrisonD123** [comment] 2022-05-27 09:14
### Closing Statement

We modified our `do_self_action` function to first take in multiple string inputs by converting `string *target` to an array of strings, `string **target`. We then modified our if-statement logic:

If the first string in the array is `"skills"` and the second element is null, we call the skilltree modules function `display_tree,` which prints all skill names out.

If the first string in the array is `"skills"` and the second element is a string, we call the skilltree function `display_skill_description,` passing in the second string as the skill name. This displays the description of the skill and will be used by the player to see what a particular skill does/means.

Harrison changed the parameters of the `do_self_action` function. Jackson and Sabine coded up the if-statement logic and called the skilltree team's functions.

**Closed as completed** 2022-05-31 13:21 UTC
Labels: x/cli, x/action-management, x/rpg-skilltrees

**Comment by ecoble** [comment] 2022-06-07 01:07
Issue Score: Excellent

Comments:
Great job implementing this, nice closing statement!
