### ISSUE TITLE
Create more robust unit-tests for skeleton code

### ISSUE THREAD

**Issue by VannStrasen** [uchicago-cs/chiventure#535] opened 2020-05-11 22:19 UTC
@steeltrapp and I are going to write unit tests for the code I wrote in the previous sprint (issue 527) to make sure that memory allocation succeeds, error codes work, etc. This will be working directly on the skilltree/skeleton_code branch, and will end with a pull request to the master branch.

**Comment by VannStrasen** [comment] 2020-05-18 06:11
After @steeltrapp and I met tonight, we decided to split up the work where I'd work on getting the tests to run (creating files, editing makefiles), as well as testing the easier half of the tests, while @steeltrapp would test the harder half of the tests. The code can be found in the branch skilltrees/skeleton_code_tests, inside of the file tests/skilltrees/test_main_functions.c. 

We might end up renaming this file as it is a bit undescriptive, but I can't currently think of a better way to describe the functions we're working on besides calling them the functions which are the main section of skilltrees functions (popping, pushing, creating structs, freeing, etc).

**Comment by VannStrasen** [comment] 2020-05-18 06:18
I've finished writing tests for the first half of the functions in skilltrees.c While I edited makefiles and other important files (main.c in the tests folder, for instance) that are important to running tests, I was having trouble compiling my tests, possibly because the tests don't work, but probably because I don't understand fully how to run tests in cmake. I'll talk with @firatciftci hopefully sometime tomorrow (if not, sometime early in the week) to see where exactly I'm going wrong.

Additionally, even though I wasn't able to check the tests, I saw some places where the skilltrees.c file was written incorrectly anyway, so I edited those. @steeltrapp and I are going to wait until PR #601 passes to PR this code, as this code is based on that PR.

**Comment by steeltrapp** [comment] 2020-05-20 23:11
My responsibility on this task was to implement unit tests for the latter functions of the skeleton code. During the first half of Sprint 3, I successfully implemented a suite of tests that tested parts of the functionality of the latter half of the code, but I found that there was more work to be done than anticipated. Namely, I still need to add tests that test the memory-related functionality of these functions. I am going to close this issue and open a new one to completet the testing suite for the skeleton code.

**Closed by steeltrapp** 2020-05-20 23:11 UTC
Labels: x/rpg-skilltrees

**Comment by firatciftci** [comment] 2020-06-16 23:14
Issue Score: ✔️+

Comments:
Great work on this issue! The only things I will point out is that there the title is a bit too generic (ideally we should be understand which team the issue is tied to from the title) and that the summary comment should have a bit more detail about the issue (in this case, what is exactly missing in the test code, etc.).
