### ISSUE TITLE
Update do_item_item_action to accommodate condition checking and attribute changes

### ISSUE THREAD

**Issue by SnowballAntrobus** [uchicago-cs/chiventure#188] opened 2019-05-28 03:57 UTC
Build upon the do_item_item_action basic prototype ( #115 ) to include condition checks, i.e. whether the item has the necessary attributes for the action to be performed, and attribute changes, i.e. the consequences of the action being requested. This will be done with game state functions

**Comment by yoonsjeong** [comment] 2019-06-06 21:09
I've created a new branch titled `actions/issue188` (makes it easy to spot) but I'm having quite a bit of difficulty. We never really fleshed out how we were going to check item_item and game-state is using a rather complex system of multiple lists.
They have a conditions list and an effects list, and each item has a list of attributes. That added to the fact that there is an indirect and and direct object means this is kind of a confusing time.

**Comment by MTUC08** [comment] 2019-06-07 12:25
Update: just finished implementing the function

**Comment by lucyyutingli** [comment] 2019-06-08 21:14
Currently, the functions are now using game-state functions, but it's not compiling at the moment since they haven't been pulled to master just yet. We'll be waiting on that before being able to make any further progress on the them.

**Comment by lucyyutingli** [comment] 2019-06-08 21:14
Sorry, I accidentally closed the issue, reopened!

**Comment by MTUC08** [comment] 2019-06-11 01:39
Update: fully implemented all functions using game state functions that will be added to master through PR #335 and created a PR to actions/dev #345 . Following the approval of that PR, we will wait until #325 goes to master and then merge to dev. After that, we will wait until #335 is merged to master and check that our tests and functions work as intended before doing a final PR to master.

**Closed** 2019-06-11 01:40 UTC
Labels: component/action-management

**Comment by MTUC08** [comment] 2019-06-11 03:43
Update: PR #346 successfully merged to dev. After #335 goes to master, and our tests and functions are found to be sound, we will do a final PR to master.

**Comment by mpcsh** [comment] 2019-06-18 01:35
Issue Score: ✓

Comments:
Good work, but the progress updates were pretty spare here - definitely could've been more frequent and more detailed.
