### ISSUE TITLE
Tests for Item Module

### ISSUE THREAD

**Issue by a-matai** [uchicago-cs/chiventure#137] opened 2019-05-18 17:07 UTC
Test internal hashtable functions

**Comment by patrickkoopmans** [comment] 2019-05-21 18:46
This issue has been changed to test the item modules rather than test internal hashtable functions.

**Comment by patrickkoopmans** [comment] 2019-05-24 21:13
What I learned from my last debugging session: 

get_x_attr is failing to return a non-NULL pointer to a attribute_t struct. This is leading to it crashing when we attempt to retrieve the union member attribute_value_t. Based on the uthash documentation, we are using the provided search functions correctly. I don't think this has to do with failing to malloc the union within the attribute_t struct. 

Where to go: 
Perhaps we need to pass in the string key differently? 
Open to suggestions.

**Comment by patrickkoopmans** [comment] 2019-05-27 00:44
What we have done so far: 
- Fully debugged! The issue was that we were using char* keys and the HASH_ADD_STR/HASH_FIND_STR macros where we should have been using HASH_ADD_KEYPTR/HASH_FIND macros. Now, our hash tables work as expected. 
- We have added certain conditions to the get_x_attr and set_x_attr function so that, for example, when someone tries to change an existing string attribute to an int, they are given an error. 
- Tests have been written for the first 3/4 of the functions (from top down) in item.c
- We have refactored the add_item_to_hash function into the room and player modules where they are now add_item_to_player and add_item_to_room. This was necessary for the hash macros to work. 

To do: 
- Finish writing tests
- Write comments for all the tests
- Pull request

**Comment by patrickkoopmans** [comment] 2019-05-27 21:12
All tests have been written, including the tests for the new functions written for Issue #157, #172, and #152. Comments have been written for every single test. Awaiting Lindsey's final comments to close.

**Comment by lindsey-hsi** [comment] 2019-05-27 21:30
Over this sprint, we found and resolved numerous bugs within our item module, the most difficult caused by the use of functions from uthash.h. This was resolved after discovering the use of char* in conjunction with HASH_ADD_TYPE/HASH_FIND_TYPE was the root of the bug. We replaced this with HASH_ADD_KEYPTR/the generalized HASH_ADD (see Patrick's comment above for a more detailed explanation of this issue). In writing the tests, we strove for maximum coverage through all possible paths in each function. At this point, we feel comfortable closing this issue and will update tests as the item module develops further to accommodate for integration. Please let us know if there are any lingering issues that need to be addressed!

**Closed by lindsey-hsi** 2019-05-27 21:30 UTC
Labels: component/game-state

**Comment by lydiafilipe** [comment] 2019-06-07 16:15
Issue Score: ✓-

Comments:
Good work on some of the updates. However, given that the issue changed so dramatically, it would have been better to close this issue and create a new one. And mention why there was this change. Also, the summary was not updated to reflect this change, and the original summary should have been more detailed - e.g. what functions were you testing? There could also have been more frequent, fine-grained updates - there are a lot of long series of commits where it seems significant work is made, but the progress is summarized in larger updates.
