### ISSUE TITLE
Work on integration of NPC movement playerclass speed stats with NPC team

### ISSUE THREAD

**Issue by Vincent-Zhang4135** [uchicago-cs/chiventure#1327] opened 2022-05-09 16:48 UTC
members: Jonathan, Vincent
task: Collaborate with NPC team on npc integration as laid out in design document

**Comment by Vincent-Zhang4135** [comment] 2022-05-09 17:57
After Jonathan met with the NPC team, we came to the conclusion that design wise, there wasn’t too much to incorporate into npc movement, and basically there is only one task, implementing player class speed stats into NPC movement, that we want to incorporate, so we created this separate issue for this and will integrate this.

**Comment by jroven** [comment] 2022-05-09 22:12
This issue is a duplicate of issue #1306, so we are closing it. All other information about this topic can be found there.

**Closed as completed by jroven** 2022-05-09 22:12 UTC
Labels: x/rpg-playerclass
