### ISSUE TITLE
Make all input text case insensitive

### ISSUE THREAD

**Issue by ecoble** [uchicago-cs/chiventure#392] opened 2019-11-22 06:27 UTC
Currently input text is case sensitive, e.g. if there is a chair in a room, "CHAIR" will not be a valid object. Make all text case insensitive

**Comment by ecoble** [comment] 2019-12-08 05:18
Input is now case insensitive, as input is converted to all caps before being parsed. WDL files must specify objects/directions/commands in all caps. Caps were picked as this was the convention for actions, however it could be switched to all lowercase instead.

**Comment by ecoble** [comment] 2020-03-06 22:41
This is issue was closed with PR #385

**Comment by borjasotomayor** [comment] 2020-06-03 14:13
Reopening this issue and putting it on the backlog because it looks like making chiventure case-insensitive is going to require deeper modifications in the code.

For example, consider the following lines from the CLI extra command example: https://github.com/uchicago-cs/chiventure/blob/23ea6d186f938a99ed5bc9ee88396ec0e7c7a904/src/cli/examples/extra-command.c#L33-L35

If you change `ROCK` to `rock` then the following happens in the CLI:

```
  > look rock
   specified item not found
  > look ROCK
   specified item not found
```

This is because the item is added to the items hash table with key `rock`, but the CLI always converts the parameter to `look` to uppercase, so it always looks up the key `ROCK` (which is not found).

In this specific case, it may be enough to modify `item_new` to convert the item identifier to uppercase, but it would be good to actually survey the rest of the code to ensure that all identifiers are internally converted to either lowercase or uppercase (preferably lowercase, since that's what case-insensitive text is usually converted to)

**Comment by samdonio** [comment] 2021-04-23 19:13
Currently, the cli parser makes all inputs fully uppercase, but this can have problems as outlined above. A way to make the cli case insensitive is to have any identifier key be made fully lowercase before being added to the respective hashtable. It seems most of these changes would be made in the game-state module i.e. probably item.h, path.h, room.h, stats.h, game_action.h, game.h, as they take in something to be added to or created in the game, and at times the hashtable. The parser however can be changed very quickly to make every input lowercase.

**Comment by mjgoodman321** [comment] 2021-04-27 17:30
Modified the parser to automatically lowercase, and added a general helper function to game-state-common so it could be applied to all of game state easily. The helper function should be moved to a more appropriate spot, preferably one that allows it to be implemented across multiple modules as needed.

**Comment by mjgoodman321** [comment] 2021-04-29 03:59
Moved case_insensitize helper function to a new module in cli for utility functions. Implemented the function inside of other cli modules.

**Comment by mjgoodman321** [comment] 2021-05-10 00:23
Created a second, more specific case_insensitize2 function and renamed original to case_insensitize1
->There may be something wrong with the case_insensitize2 function. Nothing directly appears to be wrong with it, but some of its behavior does not line up with what is expected, and it is unclear whether this is the actual function misbehaving or merely how it is interacting with the code

Additionally, with the current implementation of case insensitivity chiventure is unable to run due to elements of the game loading in from the wdl files and not being case insensitized. Attempts to begin fixing this in the load_room.c file have caused segfaults.

**Comment by mjgoodman321** [comment] 2021-05-20 21:07
Fixed the problem causing the segfault when moving into other rooms, but other actions are still not working as intended

**Comment by mjgoodman321** [comment] 2021-05-20 22:12
Determined that the reason some actions are failing is that the HASH_FIND inside of the get_action function (line 56 of game_action.c) is not finding the actions for some reasons. As such, the function as a whole is returning NULL and causing the possible_actions function to return FAILURE.

**Comment by mjgoodman321** [comment] 2021-05-25 18:36
Determined that the HASH_FIND was failing because the possible actions for an item were not being case insensitized before being loaded into that item's item_t struct, causing the function to find nothing because it was comparing a case insensitized string to a non-case insensitized string. Error has been fixed, if no further errors can be found a pull request will be made

**Comment by mjgoodman321** [comment] 2021-05-26 18:18
While launching chiventure with the test.wdl example works perfectly, attempting to launch the connedted_rooms.wdl example causes the program to segfault. The error appears to have something to do with the assign function in DFS.c

**Comment by mjgoodman321** [comment] 2021-05-28 00:01
Segfault issue fixed by merging most recent code from dev

**Comment by mjgoodman321** [comment] 2021-05-28 00:03
Collaborated with both actionmanagement and openworld teams to implement case insensitivity in their respective modules and tests

**Closed** 2021-05-31 10:48 UTC
Labels: x/cli

**Comment by ecoble** [comment] 2021-06-07 21:44
Issue Score: ✔️+

Comments:
Great job on this issue, I know it ended up being really though and you had to work though a lot of different Chiventure modules! Nice work updating the issue as well! All issues should have closing statements, even if they are closed through a PR.
