### ISSUE TITLE
Write up investigative document on current action management implementation

### ISSUE THREAD

**Issue by NuclearWaffles** [uchicago-cs/chiventure#429] opened 2020-05-01 00:23 UTC
Write a guiding document for how action, condition, and items/attributes are currently implemented in the code regarding functions, file locations, structs, and the relation between the previous three aspects

This is done with the aim of informing our design decisions moving forward with Action Blocks

This also involves designating what functions or structs we would need to change/add in order to handle custom (i.e. not pre-defined actions)

**Comment by NuclearWaffles** [comment] 2020-05-03 01:30
Read through action_management and game-state files containing action, condition, item, attribute, and effect structs. Documented my findings and the structs in this [google doc](https://docs.google.com/document/d/1IsUXp9nJlDYZAwZY9BlMCy3C6Y6K8tIx2sY_PkxWTm0/edit). 

Also drew a quick sketch illustrating the current relationship between all five aforementioned structs 
![image](https://user-images.githubusercontent.com/14869099/80896044-258ba000-8cb8-11ea-8acd-c9f3e4e7e295.png)

Key takeaways:
- There's a lot of existing structs and code that only needs some minor tweaks to support a wide range of Action Blocks (namely the effect, attribute, and condition structs)
- There are a lot of changes that need to be done which essentially steps all over the action_management team's toes so we need to communicate those clearly and designate a dedicated ambassador
- It's most likely going to be easier to design Action Blocks in tandem with Action Sequences because certain action blocks only make sense in the context of sequences (e.g. generating and referring back to a random number) . It's better to front-load some of this work, especially considering the substantial number of structs already in place that can be repurposed.
- Effect target types are going to need to be vastly expanded, or at least refactored to support expansion to more types of targets (player objects, enemy objects, _specific_ enemy objects, etc.)
- I'm not even going to touch parsing with a 10ft pole until I have to (Yes this goes against what I just said above about frontloading work. Yes I'm a hypocrite.)

**Comment by NuclearWaffles** [comment] 2020-05-03 02:07
Relayed the `attribute` struct to the RPG teams via Slack to streamline future design for both code blocks and player/entity attributes

**Comment by brentd313** [comment] 2020-05-04 13:34
I compiled a separate document, focusing on providing a thorough account of the current structures and implementation related to action management in chiventure. Zak's document provides a good amount of design-related commentary, providing insight into how various features of the current code base may provide hooks or obstacles to our design and implementation of custom actions. However, the document I put together does not attempt to provide any commentary on the design and implementation of the current codebase, but rather to provide a succinct account of how the current code works. The goal is to have this document as a resource for the rest of our team so they can have a solid foundation of understanding before we move on to thinking about design and implementation of custom actions, without needing to do an extensive code dive themselves.

[https://docs.google.com/document/d/1X3FAuUk1W_3u-f4--6ric8aKLkGk1sGF1bxkEY5M5ag/edit?usp=sharing](url)

**Comment by brentd313** [comment] 2020-05-04 14:47
Transferred my documentation of the existing code along with Zak's preliminary analysis to the Chiventure wiki. Our page is titled "Custom Actions Existing Code Review".

[https://github.com/uchicago-cs/chiventure/wiki/Custom-Actions-Existing-Code-Review](url)

**Closed** 2020-05-04 17:25 UTC
Labels: x/custom-actions

**Comment by MaxineK36** [comment] 2020-05-12 04:42
Issue Score: ✔️+

Comments:
Good work! The updates on this issue are very well fleshed-out, which makes it easy to follow the progress.
One thing to work on in the next few sprints: 
When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
